Device: cuda:0
----------------------(train)----------------------
Epoch 0/15
---------------------------------------------------
Traceback (most recent call last):
  File "train.py", line 65, in <module>
    no_wandb=args.no_wandb,
  File "/media/ssd4t/mana/GANomaly/model.py", line 52, in train
    CONFIG.batch_size, CONFIG.channel, CONFIG.input_size, CONFIG.input_size
RuntimeError: shape '[64, 1, 32, 32]' is invalid for input of size 50176
