2020-02-20 19:52:48,568 DEBUG   MainThread:22249 [wandb_config.py:_load_defaults():119] no defaults not found in config-defaults.yaml
2020-02-20 19:52:48,574 DEBUG   MainThread:22249 [meta.py:setup():94] code probe starting
2020-02-20 19:52:48,574 DEBUG   MainThread:22249 [git_repo.py:repo():30] git repository is invalid
2020-02-20 19:52:48,574 DEBUG   MainThread:22249 [meta.py:_setup_code_program():58] scan for untracked program
2020-02-20 19:52:48,574 DEBUG   MainThread:22249 [meta.py:setup():116] code probe done
2020-02-20 19:52:48,582 DEBUG   MainThread:22249 [run_manager.py:__init__():536] Initialized sync for GANomaly_mnist/liegs9z7
2020-02-20 19:52:48,584 INFO    MainThread:22249 [run_manager.py:wrap_existing_process():1134] wrapping existing process 22229
2020-02-20 19:52:48,584 WARNING MainThread:22249 [io_wrap.py:register():104] SIGWINCH handler was not None: <Handlers.SIG_DFL: 0>
2020-02-20 19:52:48,587 DEBUG   MainThread:22249 [connectionpool.py:_new_conn():959] Starting new HTTPS connection (1): pypi.org:443
2020-02-20 19:52:48,610 DEBUG   MainThread:22249 [connectionpool.py:_make_request():437] https://pypi.org:443 "GET /pypi/wandb/json HTTP/1.1" 200 41171
2020-02-20 19:52:48,626 INFO    MainThread:22249 [run_manager.py:init_run():919] system metrics and metadata threads started
2020-02-20 19:52:48,627 INFO    MainThread:22249 [run_manager.py:init_run():953] upserting run before process can begin, waiting at most 10 seconds
2020-02-20 19:52:48,647 DEBUG   Thread-14 :22249 [connectionpool.py:_new_conn():959] Starting new HTTPS connection (1): api.wandb.ai:443
2020-02-20 19:52:48,847 DEBUG   Thread-14 :22249 [connectionpool.py:_make_request():437] https://api.wandb.ai:443 "POST /graphql HTTP/1.1" 200 None
2020-02-20 19:52:48,863 INFO    Thread-14 :22249 [run_manager.py:_upsert_run():1038] saving patches
2020-02-20 19:52:48,863 INFO    Thread-14 :22249 [run_manager.py:_upsert_run():1042] saving pip packages
2020-02-20 19:52:48,865 INFO    Thread-14 :22249 [run_manager.py:_upsert_run():1044] initializing streaming files api
2020-02-20 19:52:48,866 INFO    Thread-14 :22249 [run_manager.py:_upsert_run():1051] unblocking file change observer, beginning sync with W&B servers
2020-02-20 19:52:48,867 INFO    MainThread:22249 [run_manager.py:wrap_existing_process():1151] informing user process we are ready to proceed
2020-02-20 19:52:48,874 INFO    MainThread:22249 [run_manager.py:_sync_etc():1258] entering loop for messages from user process
2020-02-20 19:52:48,877 DEBUG   Thread-15 :22249 [connectionpool.py:_new_conn():959] Starting new HTTPS connection (1): api.wandb.ai:443
2020-02-20 19:52:48,910 INFO    MainThread:22249 [run_manager.py:_sync_etc():1281] received message from user process: {"exitcode": 1}
2020-02-20 19:52:48,910 INFO    MainThread:22249 [run_manager.py:_sync_etc():1367] closing log streams and sending exitcode to W&B
2020-02-20 19:52:48,910 INFO    MainThread:22249 [run_manager.py:shutdown():1058] shutting down system stats and metadata service
2020-02-20 19:52:49,038 DEBUG   Thread-15 :22249 [connectionpool.py:_make_request():437] https://api.wandb.ai:443 "POST /graphql HTTP/1.1" 200 None
2020-02-20 19:52:49,577 INFO    Thread-3  :22249 [run_manager.py:_on_file_modified():683] file/dir modified: /media/ssd4t/mana/GANomaly/wandb/run-20200220_105248-liegs9z7/config.yaml
2020-02-20 19:52:49,586 DEBUG   Thread-3  :22249 [connectionpool.py:_new_conn():959] Starting new HTTPS connection (1): api.wandb.ai:443
2020-02-20 19:52:49,628 INFO    MainThread:22249 [run_manager.py:shutdown():1070] stopping streaming files and file change observer
2020-02-20 19:52:49,766 DEBUG   Thread-3  :22249 [connectionpool.py:_make_request():437] https://api.wandb.ai:443 "POST /graphql HTTP/1.1" 200 None
2020-02-20 19:52:49,774 INFO    MainThread:22249 [run_manager.py:_on_file_created():672] file/dir created: /media/ssd4t/mana/GANomaly/wandb/run-20200220_105248-liegs9z7/wandb-events.jsonl
2020-02-20 19:52:49,776 INFO    MainThread:22249 [run_manager.py:_on_file_created():672] file/dir created: /media/ssd4t/mana/GANomaly/wandb/run-20200220_105248-liegs9z7/output.log
2020-02-20 19:52:49,777 INFO    MainThread:22249 [run_manager.py:_on_file_created():672] file/dir created: /media/ssd4t/mana/GANomaly/wandb/run-20200220_105248-liegs9z7/requirements.txt
2020-02-20 19:52:49,779 INFO    MainThread:22249 [run_manager.py:_on_file_created():672] file/dir created: /media/ssd4t/mana/GANomaly/wandb/run-20200220_105248-liegs9z7/wandb-metadata.json
2020-02-20 19:52:49,780 INFO    MainThread:22249 [run_manager.py:_on_file_modified():683] file/dir modified: /media/ssd4t/mana/GANomaly/wandb/run-20200220_105248-liegs9z7/wandb-metadata.json
2020-02-20 19:52:49,813 DEBUG   MainThread:22249 [connectionpool.py:_new_conn():959] Starting new HTTPS connection (1): api.wandb.ai:443
2020-02-20 19:52:49,991 DEBUG   MainThread:22249 [connectionpool.py:_make_request():437] https://api.wandb.ai:443 "POST /graphql HTTP/1.1" 200 None
2020-02-20 19:52:50,792 DEBUG   Thread-7  :22249 [connectionpool.py:_new_conn():959] Starting new HTTPS connection (1): api.wandb.ai:443
2020-02-20 19:52:50,801 DEBUG   Thread-18 :22249 [connectionpool.py:_new_conn():959] Starting new HTTPS connection (1): api.wandb.ai:443
2020-02-20 19:52:50,971 DEBUG   Thread-18 :22249 [connectionpool.py:_make_request():437] https://api.wandb.ai:443 "POST /graphql HTTP/1.1" 200 None
2020-02-20 19:52:50,976 DEBUG   Thread-7  :22249 [connectionpool.py:_make_request():437] https://api.wandb.ai:443 "POST /files/llien/GANomaly_mnist/liegs9z7/file_stream HTTP/1.1" 200 None
2020-02-20 19:52:50,979 DEBUG   Thread-18 :22249 [connectionpool.py:_new_conn():959] Starting new HTTPS connection (1): storage.googleapis.com:443
2020-02-20 19:52:51,266 DEBUG   Thread-7  :22249 [connectionpool.py:_make_request():437] https://api.wandb.ai:443 "POST /files/llien/GANomaly_mnist/liegs9z7/file_stream HTTP/1.1" 200 None
2020-02-20 19:52:51,268 INFO    MainThread:22249 [run_manager.py:_sync_etc():1379] process only ran for 3 seconds, not syncing files
2020-02-20 19:52:51,268 INFO    MainThread:22249 [liegs9z7:run_manager.py:_sync_etc():1379] process only ran for 3 seconds, not syncing files
